plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

  # No need for frozen string literal comments in modern Ruby versions
  # See: https://www.jakeworth.com/posts/frozen-string-comment-yagni/
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics:
  Enabled: false
